### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by szepeviktor** [outlandishideas/oowp#8]
Please consider following a coding standard. ((WPCS,)) PSR-12 ...

After you've decided I could send a PR.

**Comment by szepeviktor** [comment]
@rasmuswinter While editing `src/PostTypeManager.php` I've detected wind-blown indentation. 🌬️

**Comment by rasmuswinter** [comment]
thanks @szepeviktor, it's something that's been in the back of my mind for a while, but i've now pushed a cleanup

**Comment by szepeviktor** [comment]
All right.

**Comment by szepeviktor** [comment]
You could tell about your stance in an EditorConfig file.
https://github.com/szepeviktor/small-project/blob/master/.editorconfig

**Comment by rasmuswinter** [comment]
done
